Sd/feat/#43 add new book authors categories
amigoscode/cohort-2-d pull request #48
Opened 2023-07-21 17:48 UTC by sarajaned

2023-07-22 13:05 UTC, amigoscode requested changes, later dismissed

2023-07-22 13:05 UTC, amigoscode commented on online-book-store/src/main/java/com/amigoscode/cohort2d/onlinebookstore/book/BookService.java
> +        BookDTOMapper.INSTANCE.modelToDTO(bookDAO.addBook(book));
I think you need. You are not returning dto to the client.

```suggestion
        bookDAO.addBook(book);
```

2023-07-22 13:05 UTC, amigoscode commented on online-book-store/src/main/java/com/amigoscode/cohort2d/onlinebookstore/category/CategoryDTO.java
> +        @Column(unique=true)
remore this. this is not en entity. its a DTO

2023-07-22 13:05 UTC, amigoscode commented on online-book-store/src/main/java/com/amigoscode/cohort2d/onlinebookstore/category/CategoryDTO.java
> +        @Column(unique=true)
or maybe I am missing something since you implement `EntityIdentifiers`

2023-07-22 13:05 UTC, amigoscode commented on online-book-store/src/test/java/com/amigoscode/cohort2d/onlinebookstore/address/AddressJpaServiceTest.java
> +    void shouldGetAddressById() {
good test. also we need another test when the address with id is not found. I just checked the implementation for `getAddressById` and its missing `orElseThrow` @JaafarF

2023-07-25 09:41 UTC, JaafarF commented on online-book-store/src/main/java/com/amigoscode/cohort2d/onlinebookstore/author/Author.java
> +            cascade = CascadeType.ALL)
We can remove the cascade, we don't want any action on books when we modify author, especially delete

2023-07-25 09:41 UTC, JaafarF commented on online-book-store/src/main/java/com/amigoscode/cohort2d/onlinebookstore/book/Book.java
> +    @ManyToMany
Let's cascade:
@ManyToMany(cascade = {
            CascadeType.PERSIST, CascadeType.MERGE,
            CascadeType.DETACH, CascadeType.REFRESH
    })

2023-07-25 09:41 UTC, JaafarF commented on online-book-store/src/main/java/com/amigoscode/cohort2d/onlinebookstore/book/Book.java
> +    @ManyToMany
Same cascade:
@ManyToMany(cascade = {
            CascadeType.PERSIST, CascadeType.MERGE,
            CascadeType.DETACH, CascadeType.REFRESH
    })

2023-07-25 09:41 UTC, JaafarF commented on online-book-store/src/main/java/com/amigoscode/cohort2d/onlinebookstore/book/BookController.java
> +        return ResponseEntity.ok()
Let's return the newly created book in the body of responseEntity (we will need its id in the client side)

2023-07-25 09:41 UTC, JaafarF commented on online-book-store/src/main/java/com/amigoscode/cohort2d/onlinebookstore/book/BookService.java
> +        Book book = new Book();
We can right away use the request book:
Book book = BookDTOMapper.INSTANCE.dtoToModel(bookDTO);

And then we can remove lines from: 72 to 79

2023-07-25 09:41 UTC, JaafarF commented on online-book-store/src/main/java/com/amigoscode/cohort2d/onlinebookstore/book/BookService.java
> +        book.setBookFormat(bookDTO.bookFormat());
Can be removed with the previous modification

2023-07-25 09:41 UTC, JaafarF commented on online-book-store/src/main/java/com/amigoscode/cohort2d/onlinebookstore/category/Category.java
> +            cascade = CascadeType.ALL)
cascade can be removed here

2023-07-26 05:56 UTC, JaafarF approved these changes

2023-07-26 07:10 UTC, JaafarF approved these changes

2023-07-26 07:11 UTC, merged