JF/feature/#47 orders setup
amigoscode/cohort-2-d pull request #68
Opened 2023-08-30 10:29 UTC by JaafarF

2023-08-30 16:44 UTC, sarajaned requested changes
Just a couple of small things I noticed

2023-08-30 16:44 UTC, sarajaned commented on online-book-store/src/main/java/com/amigoscode/cohort2d/onlinebookstore/user/User.java
> +            if (orders == null) {
Orders is initialised above when declared on line 65

2023-08-30 16:44 UTC, sarajaned commented on online-book-store/src/main/java/com/amigoscode/cohort2d/onlinebookstore/OnlineBookStoreApplication.java
unused imports

2023-08-30 16:44 UTC, sarajaned commented on online-book-store/src/main/java/com/amigoscode/cohort2d/onlinebookstore/address/AddressJpaService.java
> +    public Address getAddressReferenceById(Long addressId) {
Is this used or will it be used at a later point?

2023-08-31 10:08 UTC, JaafarF commented on online-book-store/src/main/java/com/amigoscode/cohort2d/onlinebookstore/user/User.java
> +            if (orders == null) {
You are right, 
and I just even figured out that this method is never used, so I removed it.

2023-08-31 10:08 UTC, JaafarF commented on online-book-store/src/main/java/com/amigoscode/cohort2d/onlinebookstore/OnlineBookStoreApplication.java
I removed unused imports from other files also.

2023-08-31 10:08 UTC, JaafarF commented on online-book-store/src/main/java/com/amigoscode/cohort2d/onlinebookstore/address/AddressJpaService.java
> +    public Address getAddressReferenceById(Long addressId) {
Removed

2023-08-31 16:01 UTC, sarajaned approved these changes

2023-08-31 16:01 UTC, merged